# Generated by Django 2.0.6 on 2018-06-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papaya', '0005_auto_20180614_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='static/papaya/images/empty.png', upload_to='static/papaya/images/'),
        ),
    ]
