# Generated by Django 2.0.6 on 2018-06-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papaya', '0006_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='papaya/images/empty.png', upload_to='papaya/images/'),
        ),
    ]
