# Generated by Django 2.0.6 on 2018-06-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papaya', '0007_auto_20180615_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='papaya/empty.png', upload_to='papaya/'),
        ),
    ]
