# Generated by Django 2.0.6 on 2018-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papaya', '0009_auto_20180615_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapayaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image', models.ImageField(default='papaya/static/papaya/images/empty.png', upload_to='papaya/static/papaya/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='papaya/static/papaya/images/empty.png', upload_to='papaya/static/papaya/images'),
        ),
    ]
