# Generated by Django 2.0.6 on 2018-06-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papaya', '0011_auto_20180615_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papayauser',
            name='username',
        ),
    ]
