# Generated by Django 2.0.6 on 2018-06-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papaya', '0012_remove_papayauser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='papayauser',
            name='username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
