# Generated by Django 2.0.6 on 2018-06-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papaya', '0016_auto_20180619_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papayauser',
            name='image',
            field=models.ImageField(default='papaya/static/papaya/images/anon.jpeg', upload_to='papaya/images'),
        ),
    ]
