# Generated by Django 2.0.6 on 2018-06-19 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papaya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time_created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='time_updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
